In [1]:
import os
import datetime  as dt
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
# Path
BASE_DIR = os.path.dirname(os.path.abspath('__file__'))
PARENT_DIR = os.path.dirname(BASE_DIR)
DATASET_DIR = "plantvillage_dataset/color"
METADATA_DIR = "plantvillage_dataset/csv/cleaned_metadata.csv"

#### Load metadata

In [3]:
# load dataset
df = pd.read_csv(os.path.join(PARENT_DIR, METADATA_DIR))
df.head(3)

,path,name,class,plant,disease,width,height,mode,mean_r,mean_g,mean_b,brightness,contrast,sharpness,file_size(KB),file_hash
0,d:\2026-2027\computer-vision\plantvillage_data...,00075aa8-d81a-4184-8541-b692b78d398a___FREC_Sc...,Apple___Apple_scab,Apple,Apple_scab,256,256,RGB,110.662399,130.183029,119.862732,123.143341,39.137342,12.194016,9616,841d0bf56e5ab96bb96b0953c49eb31a
1,d:\2026-2027\computer-vision\plantvillage_data...,01a66316-0e98-4d3b-a56f-d78752cd043f___FREC_Sc...,Apple___Apple_scab,Apple,Apple_scab,256,256,RGB,84.160263,97.555771,103.142639,94.179001,26.618654,14.173828,10108,b864c04c6195b89d7d7555311dbc3ca4
2,d:\2026-2027\computer-vision\plantvillage_data...,01f3deaa-6143-4b6c-9c22-620a46d8be04___FREC_Sc...,Apple___Apple_scab,Apple,Apple_scab,256,256,RGB,92.535965,125.726334,116.025253,114.686539,30.973891,20.961884,12005,2265a73c77faf5468e8b90e6dd67897c

In [38]:
len(df['class'].unique())

38

#### Chia stratified 70/15/15

In [39]:
data = df[['path', 'plant', 'disease', 'class']]
data.head()

,path,plant,disease,class
0,d:\2026-2027\computer-vision\plantvillage_data...,Apple,Apple_scab,Apple___Apple_scab
1,d:\2026-2027\computer-vision\plantvillage_data...,Apple,Apple_scab,Apple___Apple_scab
2,d:\2026-2027\computer-vision\plantvillage_data...,Apple,Apple_scab,Apple___Apple_scab
3,d:\2026-2027\computer-vision\plantvillage_data...,Apple,Apple_scab,Apple___Apple_scab
4,d:\2026-2027\computer-vision\plantvillage_data...,Apple,Apple_scab,Apple___Apple_scab

In [40]:
# chia cho train 85%, test 15%
train, test = train_test_split(
    data,
    test_size = 0.15,
    random_state = 425,
    shuffle=True,
    stratify = df['class']
)

In [41]:
train.head(5)

,path,plant,disease,class
2001,d:\2026-2027\computer-vision\plantvillage_data...,Apple,healthy,Apple___healthy
23659,d:\2026-2027\computer-vision\plantvillage_data...,"Pepper,",healthy,"Pepper,_bell___healthy"
14941,d:\2026-2027\computer-vision\plantvillage_data...,Orange,Haunglongbing_(Citrus_greening),Orange___Haunglongbing_(Citrus_greening)
4745,d:\2026-2027\computer-vision\plantvillage_data...,Cherry,healthy,Cherry_(including_sour)___healthy
42292,d:\2026-2027\computer-vision\plantvillage_data...,Tomato,Late_blight,Tomato___Late_blight

In [42]:
test.head()

,path,plant,disease,class
46138,d:\2026-2027\computer-vision\plantvillage_data...,Tomato,Spider_mites Two-spotted_spider_mite,Tomato___Spider_mites Two-spotted_spider_mite
24685,d:\2026-2027\computer-vision\plantvillage_data...,"Pepper,",healthy,"Pepper,_bell___healthy"
36950,d:\2026-2027\computer-vision\plantvillage_data...,Tomato,Bacterial_spot,Tomato___Bacterial_spot
18796,d:\2026-2027\computer-vision\plantvillage_data...,Orange,Haunglongbing_(Citrus_greening),Orange___Haunglongbing_(Citrus_greening)
33682,d:\2026-2027\computer-vision\plantvillage_data...,Squash,Powdery_mildew,Squash___Powdery_mildew

In [43]:
# lay 85% train chia val 15%
train, val = train_test_split(
    train,
    test_size= 0.15,
    random_state= 425,
    shuffle = True,
    stratify= train['class']
)

In [44]:
val.head()

,path,plant,disease,class
37915,d:\2026-2027\computer-vision\plantvillage_data...,Tomato,Bacterial_spot,Tomato___Bacterial_spot
41331,d:\2026-2027\computer-vision\plantvillage_data...,Tomato,Late_blight,Tomato___Late_blight
36078,d:\2026-2027\computer-vision\plantvillage_data...,Strawberry,Leaf_scorch,Strawberry___Leaf_scorch
10405,d:\2026-2027\computer-vision\plantvillage_data...,Corn,Northern_Leaf_Blight,Corn_(maize)___Northern_Leaf_Blight
26926,d:\2026-2027\computer-vision\plantvillage_data...,Potato,Late_blight,Potato___Late_blight

In [45]:
print("Train size: ", len(train))
print("Validation size: ", len(val))
print("Test size: ", len(test))

Train size:  39219
Validation size:  6922
Test size:  8143

In [48]:
# luu cac file train, val, test vao csv
train.to_csv(os.path.join(PARENT_DIR, "plantvillage_dataset/csv/train.csv"), index=False)
print(f"Save success file train.csv. Path: {os.path.join(PARENT_DIR, 'plantvillage_dataset/csv/train.csv')}.")
val.to_csv(os.path.join(PARENT_DIR, "plantvillage_dataset/csv/val.csv"), index=False)
print(f"Save success file val.csv. Path: {os.path.join(PARENT_DIR, 'plantvillage_dataset/csv/val.csv')}.")
test.to_csv(os.path.join(PARENT_DIR, "plantvillage_dataset/csv/test.csv"), index=False)
print(f"Save success file test.csv. Path: {os.path.join(PARENT_DIR, 'plantvillage_dataset/csv/test.csv')}.")

Save success file train.csv. Path: d:\2026-2027\computer-vision\plantvillage_dataset/csv/train.csv.
Save success file val.csv. Path: d:\2026-2027\computer-vision\plantvillage_dataset/csv/val.csv.
Save success file test.csv. Path: d:\2026-2027\computer-vision\plantvillage_dataset/csv/test.csv.

#### Thiết lập preprocessing.

In [73]:
import tensorflow as tf

# config
IMG_SIZE = (224, 224)
BATCHCH_SIZE = 32
AUTOUNE = tf.data.AUTOTUNE
SEED = 425

ValueError: Existing Python class DType already has SerializedDType as its associated proto representation. Please ensure DType has a unique proto representation.

#### Thiết lập augmentation chỉ cho Train.

In [ ]:
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip(
        mode="horizontal_and_vertical",
        seed=SEED
    ),

    tf.keras.layers.RandomRotation(
        factor=30 / 360,
        seed=SEED
    ),

    tf.keras.layers.RandomCrop(
        height=200,
        width=200,
        seed=SEED
    ),

    tf.keras.layers.Resizing(
        height=224,
        width=224
    ),

    tf.keras.layers.RandomBrightness(
        factor=0.2,
        seed=SEED
    ),

    tf.keras.layers.RandomContrast(
        factor=0.2,
        seed=SEED
    )
])

#### Chuẩn bị pipeline cho model.

In [55]:
df = pd.read_csv(os.path.join(PARENT_DIR, METADATA_DIR))

In [65]:
PATH = os.path.join(PARENT_DIR, 'plantvillage_dataset/csv/')
train_df = pd.read_csv(os.path.join(PATH, 'train.csv'))
val_df = pd.read_csv(os.path.join(PATH, 'val.csv'))
test_df = pd.read_csv(os.path.join(PATH, 'test.csv'))

In [68]:
# Dung LabelEncoder
label_encoder = LabelEncoder()
train_df["label"] = label_encoder.fit_transform(train_df['class'])
val_df["label"] = label_encoder.fit_transform(val_df["class"])
test_df["label"] = label_encoder.fit_transform(test_df["class"])
df['label'] = label_encoder.fit_transform(df['class'])

In [61]:
def load_image(path, label):
    """
    Đọc ảnh từ đường dẫn, giải mã ảnh RGB và chuẩn bị nhãn tương ứng.

    Parameters:
        path (tf.Tensor): Đường dẫn đến file ảnh.
        label (tf.Tensor): Nhãn số nguyên của ảnh.

    Returns:
        tuple: Ảnh đã đọc và nhãn tương ứng.
    """
    image = tf.io.read_file(path)
    image = tf.image.decode_image(
        image,
        channels=3,
        expand_animations=False
    )

    image = tf.image.resize(
        image,
        IMG_SIZE
    )

    image = tf.cast(
        image,
        tf.float32
    )

    return image, label

In [66]:
train_dataset = tf.data.Dataset.from_tensor_slices(
    (
        train_df["path"].values,
        train_df["label"].values
    )
)

train_dataset = train_dataset.shuffle(
    buffer_size=len(train_df),
    seed=SEED,
    reshuffle_each_iteration=True
)

train_dataset = train_dataset.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

train_dataset = train_dataset.map(
    lambda image, label: (
        data_augmentation(image, training=True),
        label
    ),
    num_parallel_calls=AUTOTUNE
)

train_dataset = train_dataset.batch(
    BATCH_SIZE
)

train_dataset = train_dataset.prefetch(
    AUTOTUNE
)

NameError: name 'tf' is not defined

In [ ]:
val_dataset = tf.data.Dataset.from_tensor_slices(
    (
        val_df["path"].values,
        val_df["label"].values
    )
)

val_dataset = val_dataset.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

val_dataset = val_dataset.batch(
    BATCH_SIZE
)

val_dataset = val_dataset.prefetch(
    AUTOTUNE
)

In [ ]:
test_dataset = tf.data.Dataset.from_tensor_slices(
    (
        test_df["path"].values,
        test_df["label"].values
    )
)

test_dataset = test_dataset.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

test_dataset = test_dataset.batch(
    BATCH_SIZE
)

test_dataset = test_dataset.prefetch(
    AUTOTUNE
)

In [ ]:
images, labels = next(iter(train_dataset))

print("Image shape:", images.shape)
print("Label shape:", labels.shape)
print("Image dtype:", images.dtype)
print("Label dtype:", labels.dtype)

In [ ]:
images, labels = next(iter(val_dataset))

print("Image shape:", images.shape)
print("Label shape:", labels.shape)

In [ ]:
import matplotlib.pyplot as plt

images, labels = next(iter(train_dataset))

plt.figure(figsize=(12, 8))

for i in range(9):
    plt.subplot(3, 3, i + 1)
    plt.imshow(
        tf.cast(images[i], tf.uint8)
    )
    plt.title(class_names[labels[i]])
    plt.axis("off")

plt.tight_layout()
plt.show()